# Generated by Django 3.2.9 on 2023-02-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_output',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrada'),
        ),
    ]
