# Generated by Django 3.2.9 on 2023-02-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_input_output_date_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input_output',
            options={'verbose_name': 'Ingresos', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AddField(
            model_name='account',
            name='pricehour',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Número de horas'),
            preserve_default=False,
        ),
    ]
