# Generated by Django 3.2.9 on 2023-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230215_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Es admin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pricehour',
            field=models.IntegerField(max_length=100, verbose_name='Valor por horas'),
        ),
    ]
